# -*- coding: utf-8 -*-
"""LOAD_MODELS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18jSbxsm6quaxHU-mTms5NroGDdJ0YHPj

## Setup Environment
- Mount the Drive
"""

from tensorflow.keras.models import load_model

model = load_model('/content/project/output/models/dl_model_ac.h5')

import pickle

# loading
with open('/content/project/output/models/tokenizer_ac.pickle', 'rb') as handle:
    tokenizer = pickle.load(handle)

# loading
with open('/content/project/output/models/mlb_ac.pickle', 'rb') as handle:
    mlb = pickle.load(handle)

import spacy

nlp = spacy.load('en')

import nltk
from nltk.corpus import stopwords

nltk.download('stopwords')
stopwords = set(stopwords.words('english'))

from gensim.models.word2vec import Word2Vec
from gensim.models import KeyedVectors

word2vec = KeyedVectors.load_word2vec_format('/content/resources/GoogleNews-vectors-negative300.bin', binary=True)

'Word2Vec Vector Size: %d' % word2vec.vector_size

from tensorflow.keras.preprocessing.sequence import pad_sequences

review = ['The food was lousy - too sweet or too salty and the portions tiny.']
tokens = []

for sent in review:
    spacy_doc = nlp(sent)
    tokens.append([t.text for t in spacy_doc])

print(tokens)

x_train = tokenizer.texts_to_sequences(tokens)

x_train = pad_sequences(x_train, maxlen=50)

mlb.inverse_transform(model.predict(x_train) > 0.5)
